### ISSUE TITLE
remove unused group

### ISSUE THREAD

**Issue by hellt** [srl-labs/intent-based-ansible-lab#2]
@wdesmedt this looks like a leftover
https://github.com/srl-labs/intent-based-ansible-lab/blob/fd9b1f349fc7d57a1544ed144f8921cd7774b9c4/inv/ansible-inventory.yml#L45-L50

**Comment by wdesmedt** [comment]
resolved by #1

**Comment by wdesmedt** [comment]
resolved by #16
