### ISSUE TITLE
Support for 'fabric intent'

### ISSUE THREAD

**Issue by wdesmedt** [srl-labs/intent-based-ansible-lab#20]
Define high-level fabric intent model that gets transformed in the custom low-level per-device intent (=device abstraction layer), currently used for underlay via the infra role. Still support input into the per-device intent to suppport configuration that is not covered by the fabric intent.
Fabric intent should define a.o. 

- 'ASN range' for BGP-underlay
- roles: spine, leaf, bleaf, dcgw
- external access handoff: vlan, vxlan 
- underlay-routing: OSPF, ISIS, BGP, BGP-UNNUMBERED -  blueprint currently defines BGP only
- ISL prefix: from which inter-switch links are getting addresses from: ipv4, /31
- VTEP prefix: from which system loopback interface gets address from (/32)
- ISL ports (leaf, spine, bleaf)
- ACCESS or DOWNLINK port (leaf)

**Comment by jbemmel** [comment]
This is starting to sound quite a bit like this self-organizing agent: https://github.com/jbemmel/srl-self-organizing/blob/main/src/auto-config-agent/models/auto-config-agent.yang#L31

Most of the above, plus:
* EVPN route reflection
* automatic LAG discovery with/without LACP
* DHCP relay

**Comment by wdesmedt** [comment]
Feat in dev branch. role: fabric (thanks @freddebacker)
