### ISSUE TITLE
Don't use environment variables for intent environment

### ISSUE THREAD

**Issue by Marlinc** [srl-labs/intent-based-ansible-lab#27]
Currently the intent environment is being specified using an environment environment, this is a non-native Ansible concept so isn't supported by for example Ansible Tower/AWX. Instead just use `env` as a fact directly as is being set in https://github.com/srl-labs/intent-based-ansible-lab/blob/dev/playbooks/roles/initialize/tasks/main.yml#L11.

This is what we have changed in our internal fork to make it work with AWX.

**Comment by wdesmedt** [comment]
Addressed with commit https://github.com/srl-labs/intent-based-ansible-lab/commit/4e2a328fdabdaffa374df0712b57b7085e629ffc

Now you can provide an extra_var 'intent_dir' from which intent files will be read, e.g. `ansible-playbook -e intent_dir=<intent_dir> ...`

**Comment by wdesmedt** [comment]
No reliance on env vars anymore. It's still there for existing CI/CD pipelines but no longer required.
