### ISSUE TITLE
Generic verision match lookup workflow

### ISSUE THREAD

**Issue by hellt** [srl-labs/intent-based-ansible-lab#6]
Often, lookup vars that match the full version is not feasible. Instead, a generic version lookup logic can be introduced:

1. first lookup vars from the full version match (as it is done today) - e.g. 23.3.3
2. if not found, lookup vars from the major version - 23.3
3. if not found, lookup vars from the year release - 23
4. if not found, lookup vars from the default location - e.g. default/vars.yml

**Comment by wdesmedt** [comment]
yes, i looked at that. As it turns out, it's not so easy to do that in Ansible (checking the presence of a file). You need a bunch of tasks to accomplish that per role.
